replicaCount: 2

image:
  repository: 000418617326.dkr.ecr.us-east-1.amazonaws.com/url-shortener
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

serviceAccount:
  create: true
  name: ""

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts: []
  tls: []

httpRoute:
  enabled: false

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
